# Generated by Django 3.1.7 on 2021-06-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('server', models.CharField(max_length=200, verbose_name='探针地址')),
                ('token', models.TextField(blank=True, max_length=200, null=True, verbose_name='探针token')),
                ('message', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('cpu', models.CharField(default='100%', editable=False, max_length=200, verbose_name='cpu')),
                ('memery', models.CharField(default='100%', editable=False, max_length=200, verbose_name='内存')),
                ('disk', models.CharField(default='100%', editable=False, max_length=200, verbose_name='总计硬盘空间')),
                ('disk2', models.CharField(default='100%', editable=False, max_length=200, verbose_name='剩余硬盘空间')),
                ('status', models.IntegerField(choices=[(1, '未连接'), (2, '正常'), (3, '异常')], default=1, editable=False, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '探针配置',
                'verbose_name_plural': '探针配置',
            },
        ),
    ]
