# Generated by Django 3.1.7 on 2021-06-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('file', models.CharField(max_length=200, verbose_name='文件')),
                ('field', models.CharField(max_length=1000, verbose_name='字段')),
                ('category', models.CharField(max_length=1000, verbose_name='脱敏类型')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '脱敏记录',
                'verbose_name_plural': '脱敏记录',
            },
        ),
    ]
