# Generated by Django 3.1.7 on 2021-06-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Natural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('total', models.FloatField(verbose_name='全部')),
                ('ava', models.FloatField(verbose_name='剩余')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '系统资源',
                'verbose_name_plural': '系统资源',
            },
        ),
    ]
