# Generated by Django 3.1.7 on 2021-06-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='标题')),
                ('desc', models.TextField(verbose_name='描述')),
                ('file', models.FileField(upload_to='upload')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '脱敏管理',
                'verbose_name_plural': '脱敏管理',
            },
        ),
    ]
